# Generated by Django 3.1.7 on 2021-03-10 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='normas',
            name='acoes',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='normas',
            name='consequencias',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='normas',
            name='descarte',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='normas',
            name='riscos',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='normas',
            name='usocorreto',
            field=models.TextField(null=True),
        ),
    ]
